services:
  exam-prep-api:
    # image: node:22-slim
    image: node:21.6.0-alpine3.19
    container_name: exam-prep-api
    ports:
      - '8889:4000'
    command: ['sh', '-c', 'npm run deploy && npm run serve']
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB} # Referencing PostgreSQL service by name
    working_dir: /app
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - exam-prep-db

  exam-prep-db:
    image: postgres:17.4-alpine3.20
    container_name: exam-prep-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5491:5432'
    volumes:
      - /volumes/exam-prep-api/postgres:/var/lib/postgresql-exam-prep/data
    restart: always
